[model]
name = 'sasrec'

hidden_units = 64

user_emb_dim = 64

item_emb_dim = 64

user_feat_emb_dim = 64

item_feat_emb_dim = 64

timediff_buckets = 20

pos_buckets = 128

dropout_rate = 0.2

[model.encoder]
hidden_units = 64
num_heads = 1
num_experts = 1
num_blocks = 1
dropout_rate = 0.2


