log_dir = "logs/"

device = 'cpu'

save_path = 'checkpoints'

[ado_infonce]
temperature = 0.07

[loss]
type = 'ado_infonce'


[loss.weight_loss]
act = false

[train]
learning_rate = 0.01
epochs = 15

